config/routes.rb
Rails.application.routes.draw do
  get "signup", to: "registration#new"
  post "signup", to: "registration#create"
  
  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "dashboard", to: "home#dashboard"

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :category, presence: true
  end
  

app/models/category.rb
class Category < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true

    has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def dashboard
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to signin_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to dashboard_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/dashboard.html.erb
<h1>Book</h1>

app/views/home/index.html.erb
<h1>Welcome to Manga World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manga-Read Comic Book Online</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <header>
      <%= image_tag 'logo.png', alt: 'Logo', class: 'logo' %>
      <h1>Manga/Anime</h1>
      <div class="sign-in">
        <% if Current.user %>
        <div class="avatar-upload">
            <input type="file" name="avatar" id="avatar" accept="image/*">
        </div>
        <div class="current-user">
          <span><%= Current.user.username %></span>
        </div>
        <div class="current-user">
          <%= button_to "Logout", logout_path, method: :delete, class: "head-link" %>
        </div>
        <% else %>
        <div class="current-user">
          <%= link_to "Sign Up", signup_path, class: "head-link" %>
        </div>
        <div class="current-user">
          <%= link_to "Sign In", signin_path, class: "head-link" %>
        </div>
        <% end %>
      </div>
    </header>
    <div class="main-content">
      <nav class="left-navigation">
        <ul>
          <li><a href="#">Category</a></li>
          <li><a href="#">Ranking</a></li>
          <li><a href="#">About</a></li>
        </ul>
      </nav>
      <div class="content">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>